In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

import sys
import os

# Get the directory where this notebook is located
current_dir = os.getcwd()
pythonprep_dir = os.path.join(current_dir, '..', '..')
pythonprep_dir = os.path.abspath(pythonprep_dir)
sys.path.append(pythonprep_dir)

from paths import main_path

In [ ]:
path_input = main_path + "/Democracy/Democracy_Main/MainAnalysis/input"
file_path = f"{path_input}/channels21st/raw_data.csv"
df = pd.read_csv(file_path)
df = df[df['Indicator'] == 'Gross capital formation (% of GDP)']
df['Country Name'].unique()
country_mapping = {
    'Bahamas, The': 'Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'Czech Republic': 'Czechia',
    'Congo, Dem. Rep.': 'Democratic Republic of Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong',
    'Iran, Islamic Rep.': 'Iran',
    'Korea, Rep.': 'South Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': 'Laos',
    'Macao SAR, China': 'Macao',
    'Russian Federation': 'Russia',
    'Slovak Republic': 'Slovakia',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Syrian Arab Republic': 'Syria',
    'West Bank and Gaza': 'Palestine',
    'Yemen, Rep.': 'Yemen',
    'Macedonia, FYR': 'North Macedonia',
    'Swaziland': 'Eswatini',
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Venezuela, RB': 'Venezuela'
}

df['Country Name'] = df['Country Name'].replace(country_mapping)
columns_to_keep = ['Country Name'] + [str(year) for year in range(2000, 2020)]
df_filtered = df[columns_to_keep]
df_pivot = df_filtered.set_index('Country Name')
df_pivot = df_pivot.dropna().reset_index()
start_year = 2001
end_year = 2019
columns_to_calculate = [str(year) for year in range(start_year, end_year + 1)]
df_growth = df_pivot[columns_to_calculate].pct_change(axis=1) * 100
df_mean_growth = df_growth.mean(axis=1)
df_pivot['mean_capital_g_2001_2019'] = df_mean_growth
df_pivot = df_pivot.drop(columns=columns_to_calculate)
df_pivot.rename(columns={'2000': 'mean_capital_g_2000', 'Country Name': 'country'}, inplace=True)
df_pivot.replace([np.inf, -np.inf], np.nan, inplace=True)
df_pivot = df_pivot.dropna()
df_pivot.to_csv(main_path + '/Democracy/Democracy_Main/MainAnalysis/input/channels21st/old_channels/capital.csv')
df_pivot

           country  mean_capital_g_2000  mean_capital_g_2001_2019
0        Argentina            17.533487                  0.561353
1          Armenia            21.922331                 -0.509265
2        Australia            26.308044                 -0.002378
3          Austria            25.926971                  0.119334
4       Azerbaijan            20.673576                  2.485226
..             ...                  ...                       ...
134        Uruguay            14.457021                  1.186568
135  United States            23.675148                 -0.173944
136     Uzbekistan            19.600012                  4.007185
137        Vietnam            29.609914                 -0.605666
138   South Africa            16.365325                  0.787517

[138 rows x 3 columns]