In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

import sys
import os

# Get the directory where this notebook is located
current_dir = os.getcwd()
pythonprep_dir = os.path.join(current_dir, '..', '..')
pythonprep_dir = os.path.abspath(pythonprep_dir)
sys.path.append(pythonprep_dir)

from paths import main_path

In [ ]:
path_input = main_path + "/Democracy/Democracy_Main/MainAnalysis/input"
file_path = f"{path_input}/channels21st/raw_data.csv"
df = pd.read_csv(file_path)
df = df[df['Indicator'] == 'Exports of goods and services (BoP, current US$)']
country_mapping = {
    'Bahamas, The': 'Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'Czech Republic': 'Czechia',
    'Congo, Dem. Rep.': 'Democratic Republic of Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong',
    'Iran, Islamic Rep.': 'Iran',
    'Korea, Rep.': 'South Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': 'Laos',
    'Macao SAR, China': 'Macao',
    'Russian Federation': 'Russia',
    'Slovak Republic': 'Slovakia',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Syrian Arab Republic': 'Syria',
    'West Bank and Gaza': 'Palestine',
    'Yemen, Rep.': 'Yemen',
    'Macedonia, FYR': 'North Macedonia',
    'Swaziland': 'Eswatini',
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Venezuela, RB': 'Venezuela'
}

df['Country Name'] = df['Country Name'].replace(country_mapping)
columns_to_keep = ['Country Name'] + [str(year) for year in range(2000, 2020)]
df_filtered = df[columns_to_keep]
df_pivot = df_filtered.set_index('Country Name')
df_pivot = df_pivot.dropna().reset_index()
start_year = 2001
end_year = 2019
columns_to_calculate = [str(year) for year in range(start_year, end_year + 1)]
df_growth = df_pivot[columns_to_calculate].pct_change(axis=1) * 100
df_mean_growth = df_growth.mean(axis=1)
df_pivot['mean_exp_2001_2019'] = df_mean_growth
df_pivot = df_pivot.drop(columns=columns_to_calculate)
df_pivot.rename(columns={'2000': 'mean_exp_2000', 'Country Name': 'country'}, inplace=True)
df_pivot.replace([np.inf, -np.inf], np.nan, inplace=True)
df_pivot = df_pivot.dropna()
df_pivot.to_csv(main_path + '/Democracy/Democracy_Main/MainAnalysis/input/channels21st/old_channels/exports.csv')
df_pivot.head()
df_pivot

           country  mean_exp_2000  mean_exp_2001_2019
0            Aruba   1.815620e+09           17.405051
1           Angola   8.187990e+09           13.903265
2          Albania   5.545000e+08           12.833419
3        Argentina   3.123692e+10            6.183569
4          Armenia   4.541743e+08           14.652253
..             ...            ...                 ...
119  United States   1.082962e+12            5.507590
120        Vietnam   1.715000e+10           16.980771
121        Vanuatu   1.569967e+08            6.868451
122   South Africa   3.699535e+10            7.045321
123         Zambia   8.719700e+08           14.937302

[124 rows x 3 columns]

In [ ]:
path_input = main_path + "/Democracy/Democracy_Main/MainAnalysis/input"
file_path = f"{path_input}/channels21st/raw_data.csv"
df = pd.read_csv(file_path)
df = df[df['Indicator'] == 'Imports of goods and services (BoP, current US$)']
country_mapping = {
    'Bahamas, The': 'Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'Czech Republic': 'Czechia',
    'Congo, Dem. Rep.': 'Democratic Republic of Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong',
    'Iran, Islamic Rep.': 'Iran',
    'Korea, Rep.': 'South Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': 'Laos',
    'Macao SAR, China': 'Macao',
    'Russian Federation': 'Russia',
    'Slovak Republic': 'Slovakia',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Syrian Arab Republic': 'Syria',
    'West Bank and Gaza': 'Palestine',
    'Yemen, Rep.': 'Yemen',
    'Macedonia, FYR': 'North Macedonia',
    'Swaziland': 'Eswatini',
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Venezuela, RB': 'Venezuela'
}

df['Country Name'] = df['Country Name'].replace(country_mapping)
columns_to_keep = ['Country Name'] + [str(year) for year in range(2000, 2020)]
df_filtered = df[columns_to_keep]
df_pivot = df_filtered.set_index('Country Name')
df_pivot = df_pivot.dropna().reset_index()
start_year = 2001
end_year = 2019
columns_to_calculate = [str(year) for year in range(start_year, end_year + 1)]
df_growth = df_pivot[columns_to_calculate].pct_change(axis=1) * 100
df_mean_growth = df_growth.mean(axis=1)
df_pivot['mean_imp_2001_2019'] = df_mean_growth
df_pivot = df_pivot.drop(columns=columns_to_calculate)
df_pivot.rename(columns={'2000': 'mean_imp_2000', 'Country Name': 'country'}, inplace=True)
df_pivot.replace([np.inf, -np.inf], np.nan, inplace=True)
df_pivot = df_pivot.dropna()
df_pivot.to_csv(main_path + '/Democracy/Democracy_Main/MainAnalysis/input/channels21st/old_channels/imports.csv')
df_pivot.head()
df_pivot

           country  mean_imp_2000  mean_imp_2001_2019
0            Aruba   1.505844e+09           14.410044
1           Angola   5.738980e+09            9.933093
2          Albania   1.350300e+09            9.449004
3        Argentina   3.306880e+10            8.625768
4          Armenia   9.859513e+08           12.571172
..             ...            ...                 ...
119  United States   1.452651e+12            5.058003
120        Vietnam   1.732500e+10           16.580399
121        Vanuatu   1.470872e+08            8.441900
122   South Africa   3.307496e+10            8.099159
123         Zambia   1.312317e+09           11.076675

[124 rows x 3 columns]